### ISSUE TITLE
Add second type to pokemon's card

### ISSUE THREAD

**Issue by Gage-Giovanni** [Gage-Giovanni/pokesearch#1]
Currently, only the first type of each pokemon is shown, however, many have two types. Add a way for the user to see both types on the pokemon's card.

Refer to the [PokeAPI](https://pokeapi.co/) docs for information on how to retrieve each type.

**Comment by ildebr** [comment]
Can you assing this to me?

**Comment by Gage-Giovanni** [comment]
Sorry for the delay, I've assigned this issue to you

**Comment by ildebr** [comment]
Hey, no problem. Will work on it asap

**Comment by ildebr** [comment]
did you have a look at the pull request?

**Comment by Gage-Giovanni** [comment]
Thanks for your contribution, I've merged the pull request

**Comment by ildebr** [comment]
Great! good to help
